name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Flamingo/Flamingo.csproj
    - name: Build
      run: dotnet build ./Flamingo/Flamingo.csproj --no-restore
    - name: Test
      run: dotnet test ./Flamingo/Flamingo.csproj --no-build --verbosity normal
